### ISSUE TITLE
dimension mismatch

### ISSUE THREAD

**Issue by sriharsha0806** [sacmehta/ESPNet#2]
Hi I ran your code. I am getting follwoing error: 
"""
Total network parameters: 349449
Data statistics
[72.39231  82.908936 73.1584  ] [45.31922  46.152893 44.914833]
[ 1.5422179  6.085514  10.492059  10.492059  10.492059  10.492059
 10.492059  10.492059  10.492059  10.492059  10.492059  10.492059
 10.492059  10.492059  10.492059  10.492059  10.492059  10.492059
 10.492059   5.2713513]
Learning rate: 0.0005
Traceback (most recent call last):
  File "main.py", line 413, in <module>
    trainValidateSegmentation(parser.parse_args())
  File "main.py", line 339, in trainValidateSegmentation
    train(args, trainLoader_scale1, model, criteria, optimizer, epoch)
  File "main.py", line 103, in train
    loss = criterion(output, target_var)
  File "/users/sriharsha.annamaneni/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/users/sriharsha.annamaneni/ESPNet/train/Criteria.py", line 23, in forward
    return self.loss(F.log_softmax(outputs, 1), targets)
  File "/users/sriharsha.annamaneni/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/users/sriharsha.annamaneni/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 147, in forward
    self.ignore_index, self.reduce)
  File "/users/sriharsha.annamaneni/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1051, in nll_loss
    return torch._C._nn.nll_loss2d(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: input and target batch or spatial sizes don't match: target [6 x 768 x 1536], input [6 x 20 x 96 x 192] at /opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THCUNN/generic/SpatialClassNLLCriterion.cu:24

"""
There is a dimension mismatch between image from model and target image

**Comment by sacmehta** [comment]
ESPNet-C expects the output dimensions to be 1/8th of input image size. Please pass --scaleIn 8 as a parameter to train ESPNet-C.

**Comment by sriharsha0806** [comment]
ok
